### ISSUE TITLE
Add ability for user to update profile information in frontend

### ISSUE THREAD

**Issue by cwojtak** [cwojtak/GatorSecurity#15]
Currently it leads to another page, but the profile cannot be edited.

**Comment by UFdylantosh** [comment]
Issue: The Edit Profile button on localhost:3000/myprofile links to localhost:3000/userInfo. A user's email and first name can be seen, but the information cannot be edited. 

Current Fix: Added the ability for a user to input a new first and last name for the user's profile. The user can successfully edit those two fields and change those two attributes.

Known Issues: Experimented with altering the user's email and password on the page. However, altering those properties caused rendering issues due to how backend currently works, and the method seems insecure.

Suggestions: Create a separate page, form, and button for a user to be able to alter their email address or password, then log them out.
